name: weather_test
description: "Weather Test"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  fast_immutable_collections: ^10.2.4

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11

  fake_async: ^1.3.1
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  golden_toolkit: ^0.15.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf